base_folder: /msnovelist
batch_size: 256
cv_fold: 1
cv_folds: 10
db_path_train:
  construct_from: smiles
  fp_map: "/data/MSNovelist-data/fingerprint_map_pseudo.tsv"
  path: "/data/MSNovelist-data/mist.db"
  pipeline_options:
    embed_X: false
    unpackbits: true
    fingerprint_selected: fingerprint_sampled
  reload_smiles_pubchem: false
db_path_eval:
  construct_from: smiles
  fp_map: "/data/MSNovelist-data/fingerprint_map_pseudo.tsv"
  path: "/data/MSNovelist-data/mist_val.db"
  pipeline_options:
    embed_X: false
    unpackbits: FALSE
    unpack: FALSE
    fingerprint_selected: fingerprint_degraded
  reload_smiles_pubchem: false
# db_path_template:
#   construct_from: smiles
#   fp_map: /contrib/fingerprinter_cli/csi_fingerid_mod.tsv
#   path: /msnovelist-data/minimal-dataset/sirius6-minimal.db
#   pipeline_options:
#     embed_X: false
#   reload_smiles_pubchem: false
db_path_sampler:
  construct_from: smiles
  fp_map: "/data/MSNovelist-data/fingerprint_map_pseudo.tsv"
  path: "/data/MSNovelist-data/mist_val.db"
  pipeline_options:
    embed_X: false
    unpackbits: true
  reload_smiles_pubchem: false
db_pubchem: /msnovelist/data/pubchem-dummy/pubchem_ref_dummy.db
decoder_config:
  clip_invalid_counts: false
  tokenization: tokens_process
decoder_name: beam_search
epochs: 30
eval_counter: ''
eval_detail: false
eval_folder: /tmp/mistnovelist-eval/
eval_fingerprint_all: false
eval_id: ''
eval_k: 10
eval_kk: 64
eval_n: 8
eval_n_total: 20
eval_steps: 128
eval_temperature: 1.0
eval_top_n: 1
evaluation_set: val
f1_cutoff: 0.5
fingerprinter_cache: /tmp/fingerprint_cache.db
normalizer_path: /contrib/fingerprinter_cli/bin/smiles_normalizer
sirius_path: /contrib/sirius/bin/sirius
fp_map: "/data/MSNovelist-data/fingerprint_map_pseudo.tsv"
fp_map_evaluation: "/data/MSNovelist-data/fingerprint_map_pseudo.tsv"
fp_overlay_method: none
fp_source: ''
hdf5_lock: 'FALSE'
log_folder: /tmp/
model_config:
  loss_weights:
    out_nhydrogen: 0.03
    out_smiles: 1
  use_auxiliary_counter: true
  use_fingerprint: true
  use_hydrogen_estimator: true
  encoder_dropout: [0, 0]
  encoder_input_dropout: None
model_name: models.model_flex_20190401
model_tag: mistnovelist
pipeline_encoder:
- fingerprint_selected
- mol_form
- n_hydrogen
pipeline_reference:
- smiles_canonical
- fingerprint_degraded
pipeline_x:
- fingerprint_selected
- mol_form
- tokens_X
pipeline_x_eval: []
pipeline_y:
- tokens_y
- n_hydrogen
random_seed_global: ''
rerank_sirius_results_n: 99999
#sampler_name: fp_sampling.cv_sampler_direct
sampler_name: "basic_tp_fp"
sampler_config:
  tpr: 0.7
  fpr: 0.01
  unchanged_rate: 0.01
steps_per_epoch: -1
steps_per_epoch_validation: -1
tensorflow_trace: false
training_id: ''
training_set: train
training_verbose: 1
validation_set: validate
weights: w-02-0.086-0.079.hdf5
weights_folder: /data/MSNovelist-data/weights
